# Generated by Django 4.2.1 on 2023-05-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_person_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countchicken',
            name='department',
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uers_department', to='app.department'),
        ),
    ]
