# Generated by Django 4.2.1 on 2023-05-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_countchicken_department_person_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countchicken',
            name='user',
        ),
    ]
